### ISSUE TITLE
Does it support iOS or android

### ISSUE THREAD

**Issue by wangyue12** [unity3d-jp/USDForUnity#5]
Can the unity plugin support iOS or android platform?Hoping to hear from you!

**Comment by i-saint** [comment]
USD' source is hard to porting and I won't do it. instead of it, I'm working on USD to Unity asset converter.  if USD is converted to asset, it can play on any platforms Unity supports (just like built-in FBX importer is doint).
Mesh and Xform animation are already done but vertex cache animation will take awhile.
